[package]
name = "inkpaper-simulator"
version = "0.1.0"
edition = "2024"

[features]
default = []
defmt = ["inkpaper-app/defmt", "inkpaper-ui/defmt"]

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
embedded-graphics = { workspace = true }
embedded-graphics-simulator = { workspace = true }
image = { workspace = true }
inkpaper-app = { path = "../app" }
inkpaper-ui = { path = "../ui", features = ["embedded-graphics", "ttf"] }
static_cell = { workspace = true }
