[package]
name = "inkpaper-reader"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
hypher = { version = "0.1.8", default-features = false, features = ["alloc", "english"] }
inkpaper-epub = { path = "../epub" }
unicode-linebreak = { workspace = true }

[dev-dependencies]
futures-lite = { workspace = true }