[workspace]
resolver = "3"
members = ["crates/*", "firmware/*"]
default-members = ["crates/*"]

[workspace.dependencies]
embedded-graphics = "0.8.2"
embedded-graphics-simulator = "0.8.0"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
defmt = "1.1.1"
heapless = "0.9.3"
# TODO: update when released on crates.io
esp-backtrace = { git = "https://github.com/esp-rs/esp-hal", rev = "160b107" }
esp-bootloader-esp-idf = { git = "https://github.com/esp-rs/esp-hal", rev = "160b107" }
esp-hal = { git = "https://github.com/esp-rs/esp-hal", rev = "160b107" }
esp-println = { git = "https://github.com/esp-rs/esp-hal", rev = "160b107" }
esp-rtos = { git = "https://github.com/esp-rs/esp-hal", rev = "160b107" }


[profile.firmware]
inherits = "release"
debug = 2
lto = "fat"
codegen-units = 1