[workspace]
resolver = "3"
members = ["crates/*", "firmware/*"]
default-members = ["crates/*"]

[workspace.dependencies]
embedded-graphics = "0.8.2"
embedded-graphics-simulator = "0.8.0"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
heapless = "0.9.3"

[profile.firmware]
inherits = "release"
debug = true
lto = "fat"
codegen-units = 1