[package]
name = "inkpaper-app"
version = "0.1.0"
edition = "2024"

[features]
default = ["hinting"]
defmt = ["inkpaper-ui/defmt"]
# draw text from autohinted glyph outlines
hinting = ["inkpaper-ui/hinting"]

[dependencies]
inkpaper-epub = { path = "../epub" }
inkpaper-reader = { path = "../reader" }
inkpaper-trace = { path = "../trace" }
inkpaper-ui = { path = "../ui", features = ["alloc"] }
minicbor = { version = "2.3.0", default-features = false, features = ["alloc", "derive"] }
zune-core = { version = "=0.5.3", default-features = false }
zune-jpeg = { version = "=0.5.15", default-features = false }
zune-png = { version = "=0.5.2", default-features = false }

[dev-dependencies]
futures-lite = { workspace = true }
