[target.xtensa-esp32s3-none-elf]
runner = [
    "probe-rs",
    "run",
    "--chip=esp32s3",
    "--preverify",
    "--always-print-stacktrace",
    "--log-format",
    "{t:dimmed} {L:severity:bold} {s:werror}\n\t{fff:dimmed}:{l:dimmed}",
]

rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Wl,-Tlinkall.x",
    "-C", "link-arg=-Tdefmt.x"
]

[alias]
xtask = "run -p xtask --"

[env]
DEFMT_LOG = "debug,esp_rtos=off,esp_hal=off"

[unstable]
build-std = ["core", "alloc"]
