[package]
name = "inkpaper-ui-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
inkpaper-ui-style-schema = { path = "../ui-style-schema" }
proc-macro2 = { workspace = true }
quote = { workspace = true }
roxmltree = "0.21.1"
rstml = "0.13.0"
svgtypes = "0.16.1"
syn = { workspace = true, features = ["full"] }
