[package]
name = "inkpaper-x4-pro"
version = "0.1.0"
edition = "2024"

[dependencies]
# internal deps
bm8563 = { path = "../../crates/bm8563", features = ["defmt"] }
cw2017 = { path = "../../crates/cw2017", features = ["defmt"] }
epd-bus = { path = "../../crates/epd-bus", features = ["defmt"] }
frontlight = { path = "../../crates/frontlight", features = ["defmt"] }
gt911 = { path = "../../crates/gt911", features = ["defmt"] }
inkpaper-app = { path = "../../crates/app", features = ["defmt"] }
inkpaper-ui = { path = "../../crates/ui", features = ["defmt"] }
ssd1677 = { path = "../../crates/ssd1677", features = ["defmt"] }
uc8179 = { path = "../../crates/uc8179", features = ["defmt"] }
uc8279-x4 = { path = "../../crates/uc8279-x4", features = ["defmt"] }
xteink-display-probe = { path = "../../crates/xteink-display-probe", features = ["defmt"] }

defmt = { workspace = true }
embedded-graphics = { workspace = true }
embedded-hal-async = { workspace = true }
hadris-fat = { version = "2.2.0", default-features = false, features = ["async", "defmt", "lfn", "read"] }
hadris-io = { version = "2.2.0", default-features = false, features = ["async"] }
heapless = { workspace = true, features = ["defmt"] }

[target.'cfg(target_arch = "xtensa")'.dependencies]
aligned = "0.4.3"
embassy-embedded-hal = { version = "0.6.0", features = ["defmt"] }
embassy-executor = { version = "0.10.0", features = ["defmt"] }
embassy-futures = "0.1.2"
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime-ms"] }
block-device-driver = "0.2.0"
esp-backtrace = { workspace = true, features = ["esp32s3", "panic-handler", "defmt"] }
esp-bootloader-esp-idf = { workspace = true, features = ["esp32s3", "defmt"] }
esp-hal = { workspace = true, features = ["esp32s3", "unstable", "defmt"] }
esp-rtos = { workspace = true, features = ["esp32s3", "embassy", "defmt"] }
rtt-target = { version = "0.6.2", features = ["defmt"] }
sdio = { version = "0.5.1", features = ["defmt"] }
static_cell = { workspace = true }
